default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: task_manager_production
  username: deployuser
  password: h@Rp1@78579467
  host: 127.0.0.1
  port: 5433

cable:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost/#{ENV.fetch("RAILS_ENV") { "task_manager_production" }}" } %>

queue:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost/#{ENV.fetch("RAILS_ENV") { "task_manager_production" }}" } %>

cache:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost/#{ENV.fetch("RAILS_ENV") { "task_manager_production" }}" } %>
